import Link from "next/link";
import { ArrowLeft, ArrowRight, BarChart3, BookOpen, FileCheck2 } from "lucide-react";
import { notFound } from "next/navigation";

const data={
  "business-credit":{icon:BarChart3,kicker:"Financial credibility",title:"Business Credit Consulting",lead:"Prepare for financing conversations with a clearer profile, organized documentation, and a realistic readiness plan.",outcomes:["Understand how your current business profile presents","Identify documentation and consistency gaps","Prioritize responsible readiness steps before applying"],includes:["Business profile review","Documentation inventory","Readiness action plan","Educational strategy session"],note:"Jour et Nuit does not guarantee approvals, scores, limits, or terms. Decisions remain with third parties."},
  "documents-filing":{icon:FileCheck2,kicker:"Professional structure",title:"Documents & Filing Support",lead:"Replace scattered records and administrative uncertainty with a more organized, professionally maintained foundation.",outcomes:["Clarify which administrative items require attention","Prepare and organize agreed business documents","Create a more manageable compliance rhythm"],includes:["Formation guidance","Administrative document preparation","Registration and filing coordination","Record organization support"],note:"We are not a law firm. Legal, tax, and regulated matters should be reviewed by appropriately licensed professionals."},
  "business-education":{icon:BookOpen,kicker:"Confident leadership",title:"Business Education",lead:"Build the practical understanding to make better decisions, ask sharper questions, and lead the business with more confidence.",outcomes:["Understand foundational business concepts in plain language","Connect strategy to your current stage and goals","Leave with practical actions you can apply"],includes:["Private coaching","Workshops and webinars","Templates and guided resources","Growth strategy consulting"],note:"Educational services provide general business information and strategic guidance, not legal, tax, or individualized financial advice."}
} as const;
export function generateStaticParams(){return Object.keys(data).map(slug=>({slug}))}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=data[slug as keyof typeof data];if(!s)notFound();const Icon=s.icon;return <main className="subpage"><header className="subnav"><Link href="/" className="brand"><span className="brand-mark">JN</span><span><strong>Jour et Nuit</strong><small>Concierge</small></span></Link><Link href="/#services" className="back"><ArrowLeft size={15}/> All services</Link></header><section className="service-page"><div className="service-title"><Icon/><p className="kicker">{s.kicker}</p><h1>{s.title}</h1><p>{s.lead}</p><Link className="button button-primary" href="/consultation">Request a strategy session <ArrowRight size={16}/></Link></div><div className="service-details"><section><p className="kicker">What this helps you do</p>{s.outcomes.map((o,i)=><article key={o}><span>0{i+1}</span><p>{o}</p></article>)}</section><section><p className="kicker">A focused engagement may include</p><ul>{s.includes.map(x=><li key={x}>{x}</li>)}</ul></section><aside>{s.note}</aside></div></section></main>}
